### ISSUE TITLE
tmux_cwd_sync_now optionally select a pane

### ISSUE THREAD

**Issue by 4l1fe** [joouha/ranger_tmux#5]
Hey. What do you think about having an option for a command `tmux_cwd_sync_now`?
I often press `xc` and always go to a pane i synced and think there might be an option something like `tmux_cwd_sync_now select=True` or `tmux_cwd_sync_now focus=True` to reduce the repeatable action.

Then this option can be set up as default in a config or one more shortcut is added.

**Comment by joouha** [comment]
Yes, I think this is a good idea and something I would probably use myself!

**Comment by 4l1fe** [comment]
Ok, it will take some time to figure out how to implement it, that's a standard feature i mean a command option so shouldn't be complicated.

I'll send a PR with a solution.

**Comment by joouha** [comment]
Hey - I was looking to see how difficult this would be to implement, but it turned out to be really simple (hope you don't mind).

Do you mind testing #7 for me?

**Comment by 4l1fe** [comment]
> Hey - I was looking to see how difficult this would be to implement, but it turned out to be really simple (hope you don't mind).
> 
> Do you mind testing #7 for me?


Tested, it's working well. At the moment, i don't see any issue...

**Comment by joouha** [comment]
This is now in v1.0.8
