### ISSUE TITLE
ranger_tmux.drop not workin

### ISSUE THREAD

**Issue by Joarell** [joouha/ranger_tmux#6]
### Hi there!
I hope you are doing great!
This plugin is really great, thank you for having had this idea!

I would like to ask you some assistance on the `drop down` feature.
I couldn't figure it out what is wrong on my system settings cause it's not working properly.
Attached you find the images about the python output when I run the command  `python -m ranger_tmux.drop`.
I have installed the plugin using pip command.

Thank you in advance and have a great day!
![ranger_plugin](https://user-images.githubusercontent.com/42722369/191815298-ff249f65-3b07-45a8-ba8b-c2df84c0682a.png)
![ranger_plugin1](https://user-images.githubusercontent.com/42722369/191815307-13d2e5fb-4556-4293-bb56-41000fd1b980.png)

**Comment by joouha** [comment]
Hi,

Thanks! I'm doing very well :-)

What version of tmux are you using?

What output do you get if you run the following?:

```bash
tmux display -t '{top}' -p "#{pane_id}|#{pane_start_command}|#{pane_pid}"
```

**Comment by Joarell** [comment]
Great!
So, I'm using the `tmux -version 3.3a`.
### This is the output of the coommand as you suggested:
`"which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l /bin/zsh || /bin/zsh"|208017
`

**Comment by Joarell** [comment]
# Bingo!
I found my error!
On my tmux.conf I had the line below:
`set-option -g default-command "which reattach-to-user-namespace > /dev/null && reattach-to-user-namespace -l $SHELL || $SHELL"
`
When I have commented that line it's worked perfectly!
Thank you so much for your attention and assistance!
I'll close the my personal "issue"... Rsrssrsr... As soon as you send me your reply.

I wish you best!
Thank you again for this plugin it's really great!
Have a great day and be fine! 
Warmest regards from Brazil!
